Repository ProvedCode/frontend, pull requests merged in 2023-05, with the labels that each got.

#83 created footer
  package-lock.json
  package.json
  src/components/Layout/Footer/Footer.jsx
  src/components/Layout/Footer/Footer.module.scss
  src/components/ListProofsPage/ListProofsPage.jsx
  src/components/ProfilePage/components/ProfileListProofs/ProfileListProofs.jsx
  src/components/TalentPage/components/ListProofs/ListProofs.jsx
  src/components/TalentPage/components/ListProofs/components/ProofBlock/components/Kudos.jsx
Labels: frontend, General

#91 Fixed bugs
  src/components/ListProofsPage/ListProofsPage.jsx
  src/components/ProfilePage/components/ProfileListProofs/ProfileListProofs.jsx
  src/components/TalentPage/components/ListProofs/ListProofs.jsx
  src/components/TalentPage/components/ListProofs/components/ProofBlock/components/Kudos.jsx
  src/services/api-services.js
Labels: frontend

#92 Pagination talent fix
  src/components/ListProofsPage/ListProofsPage.jsx
  src/components/ProfilePage/components/ProfileListProofs/ProfileListProofs.jsx
  src/components/TalentPage/components/ListProofs/ListProofs.jsx
  src/services/api-services.js
Labels: frontend, stage 2

#96 87 sponsor profile
  package-lock.json
  src/App/App.jsx
  src/components/Layout/AuthModal/components/Register/Register.jsx
  src/components/Layout/AuthModal/components/Register/Register.module.scss
  src/components/Layout/Header/Header.jsx
  src/components/ListProofsPage/ListProofsPage.jsx
  src/components/ListProofsPage/index.js
  src/components/ProfilePage/components/ProfileListProofs/components/ProfileProofBlock/ProfileProofBlock.module.scss
  src/components/SponsorPage/SponsorPage.jsx
  src/components/SponsorPage/SponsorPage.module.scss
  src/components/SponsorPage/components/SponsorAbout/SponsorAbout.jsx
  src/components/SponsorPage/components/SponsorAbout/SponsorAbout.module.scss
  src/components/SponsorPage/components/SponsorData/SponsorData.jsx
  src/components/SponsorPage/components/SponsorData/SponsorData.module.scss
  src/components/SponsorPage/components/SponsorData/index.js
  src/components/SponsorPage/index.js
  src/context/UserContext/UserContext.jsx
  src/services/api-services.js
Labels: frontend, User story #2, stage 3.2

#98 94 sponsor kudos
  src/components/Layout/AuthModal/components/Login/Login.jsx
  src/components/Layout/AuthModal/components/Register/Register.jsx
  src/components/Layout/Header/Header.jsx
  src/components/ListProofsPage/ListProofsPage.jsx
  src/components/ListProofsPage/ListProofsPage.module.scss
  src/components/ProfilePage/components/ProfileListProofs/components/ProfileProofBlock/ProfileProofBlock.jsx
  src/components/ProfilePage/components/ProfileListProofs/components/ProfileProofBlock/ProfileProofBlock.module.scss
  src/components/SponsorPage/SponsorPage.jsx
  src/components/SponsorPage/components/SponsorAbout/SponsorAbout.jsx
  src/components/SponsorPage/components/SponsorData/SponsorData.jsx
  src/components/SponsorPage/components/SponsorData/SponsorData.module.scss
  src/components/SponsorPage/components/SponsorData/validate.js
  src/components/TalentPage/components/ListProofs/components/ProofBlock/ProofBlock.jsx
  src/components/TalentPage/components/ListProofs/components/ProofBlock/ProofBlock.module.scss
  src/components/TalentPage/components/ListProofs/components/ProofBlock/components/Kudos/Kudos.jsx
  src/components/TalentPage/components/ListProofs/components/ProofBlock/components/Kudos/Kudos.module.scss
  src/components/TalentPage/components/ListProofs/components/ProofBlock/components/Kudos/index.js
  src/components/TalentsListPage/components/TalentsList/components/TalentCard/TalentCard.jsx
  src/context/UserContext/UserContext.jsx
  src/services/api-services.js
Labels: frontend, stage 3.2

#103 skills for proofs
  package-lock.json
  package.json
  src/components/ProfilePage/components/AddingProofsForm/AddingProofsForm.jsx
  src/components/ProfilePage/components/AddingProofsForm/AddingProofsForm.module.scss
  src/components/ProfilePage/components/AddingProofsForm/components/CustomClearIndicator/CustomClearIndicator.jsx
  src/components/ProfilePage/components/AddingProofsForm/components/CustomClearIndicator/index.js
  src/components/ProfilePage/components/AddingProofsForm/components/ValueCross/ValueCross.jsx
  src/components/ProfilePage/components/AddingProofsForm/components/ValueCross/index.js
  src/components/ProfilePage/components/AddingProofsForm/validate.js
  src/components/ProfilePage/components/ProfileListProofs/ProfileListProofs.jsx
  src/components/ProfilePage/components/ProfileListProofs/components/ProfileProofBlock/ProfileProofBlock.jsx
  src/components/ProfilePage/components/ProfileListProofs/components/ProfileProofBlock/ProfileProofBlock.module.scss
  src/components/ProfilePage/components/TalentData/TalentData.jsx
  src/components/TalentPage/components/ListProofs/components/ProofBlock/ProofBlock.jsx
  src/components/TalentPage/components/ListProofs/components/ProofBlock/ProofBlock.module.scss
  src/components/TalentsListPage/components/TalentsList/components/TalentCard/TalentCard.jsx
  src/services/api-services.js
Labels: frontend, User story #1, stage 4.1

#107 106 profile talents skills
  package-lock.json
  src/components/Layout/Header/Header.jsx
  src/components/ListProofsPage/ListProofsPage.jsx
  src/components/ProfilePage/ProfilePage.jsx
  src/components/ProfilePage/components/About/About.jsx
  src/components/ProfilePage/components/AddingProofsForm/AddingProofsForm.jsx
  src/components/ProfilePage/components/ProfileListProofs/components/ProfileProofBlock/ProfileProofBlock.jsx
  src/components/ProfilePage/components/ProfileListProofs/components/ProfileProofBlock/ProfileProofBlock.module.scss
  src/components/ProfilePage/components/TalentData/TalentData.jsx
  src/components/ProfilePage/components/TalentData/TalentData.module.scss
  src/components/ProfilePage/components/TalentData/components/ClearOneSkill/ClearOneSkill.jsx
  src/components/ProfilePage/components/TalentData/components/ClearTalentSkills/ClearTalentSkills.jsx
  src/components/SponsorPage/components/SponsorData/validate.js
  src/components/TalentPage/components/ListProofs/components/ProofBlock/ProofBlock.jsx
  src/components/TalentPage/components/ListProofs/components/ProofBlock/components/Kudos/Kudos.jsx
  src/context/UserContext/UserContext.jsx
  src/services/api-services.js
  src/shared/components/ModalWindow/ModalWindow.jsx
Labels: frontend, User story #1, stage 4.2

#108 bug fixed and upload image
  src/components/Layout/AuthModal/components/Login/Login.jsx
  src/components/ListProofsPage/ListProofsPage.jsx
  src/components/ProfilePage/ProfilePage.jsx
  src/components/ProfilePage/components/About/About.jsx
  src/components/ProfilePage/components/TalentData/TalentData.jsx
  src/components/ProfilePage/components/TalentData/TalentData.module.scss
  src/components/TalentPage/components/ListProofs/ListProofs.jsx
  src/components/TalentPage/components/ListProofs/ListProofs.module.scss
  src/components/TalentsListPage/components/TalentsList/components/TalentCard/TalentCard.jsx
  src/services/api-services.js
Labels: frontend, stage 4.2
