Repository ProvedCode/frontend, pull requests merged in 2023-04, with the labels that each got.

#45 43 remarks correction
  src/App/App.jsx
  src/components/Layout/AuthModal/AuthModal.jsx
  src/components/Layout/AuthModal/components/Login/Login.jsx
  src/components/Layout/Footer/Footer.jsx
  src/components/Layout/Main/Main.jsx
  src/components/NotFoundPage/NotFoundPage.jsx
  src/components/NotFoundPage/NotFoundPage.module.scss
  src/components/NotFoundPage/images/notfound.png
  src/components/NotFoundPage/index.js
  src/components/TalentsListPage/TalentsListPage.jsx
  src/components/TalentsListPage/components/Pagination/Pagination.jsx
  src/components/TalentsListPage/components/Pagination/components/PageNumber/PageNumber.jsx
  src/components/TalentsListPage/components/TalentsList/TalentsList.jsx
  src/components/TalentsListPage/components/TalentsList/components/TalentCard/TalentCard.jsx
  src/context/TalentsContext/index.js
  src/context/UserContext/index.js
  src/hoc/RequireAuth.jsx
  src/index.jsx
  src/services/api-services.js
Labels: frontend, User story #1

#46 the talent's page has created
  package-lock.json
  src/components/Layout/Header/Header.jsx
  src/components/Layout/Header/Header.module.scss
  src/components/TalentPage/TalentPage.jsx
  src/components/TalentPage/TalentPage.module.scss
  src/components/TalentsListPage/components/TalentsList/components/TalentCard/TalentCard.jsx
  src/context/TalentsContext/TalentsContext.jsx
  src/context/UserContext/UserContext.jsx
  src/hooks/index.js
  src/hooks/useTalent.js
  src/services/api-services.js
  src/shared/images/github.svg
  src/shared/images/linkedin.svg
Labels: frontend, User story #2

#66 58 talents proofs
  src/components/TalentPage/components/ListProofs/ListProofs.jsx
  src/components/TalentPage/components/ListProofs/components/ProofBlock/ProofBlock.jsx
  src/components/TalentPage/components/ListProofs/components/ProofBlock/ProofBlock.module.scss
  src/components/TalentPage/components/ListProofs/components/ProofBlock/index.js
  src/components/TalentPage/components/ListProofs/index.js
  src/components/TalentsListPage/TalentsListPage.jsx
  src/services/api-services.js
Labels: frontend, User Story #8

#65 Added page of common proofs and realised filter of them
  src/App/App.jsx
  src/components/Layout/Header/Header.jsx
  src/components/Layout/Header/Header.module.scss
  src/components/ListProofsPage/ListProofsPage.jsx
  src/components/ListProofsPage/ListProofsPage.module.scss
  src/components/TalentPage/TalentPage.jsx
  src/components/TalentPage/components/ListProofs/components/ProofBlock/images/fire.svg
  src/components/TalentPage/components/ProofBlock/ProofBlock.jsx
  src/components/TalentPage/components/ProofBlock/ProofBlock.module.scss
  src/components/TalentPage/components/ProofBlock/index.js
  src/components/TalentsListPage/TalentsListPage.jsx
  src/components/TalentsListPage/components/TalentsList/TalentsList.module.scss
Labels: frontend, User Story #6

#67 60 add authorization
  package-lock.json
  package.json
  src/App/App.jsx
  src/components/Layout/AuthModal/AuthModal.jsx
  src/components/Layout/AuthModal/components/Login/Login.jsx
  src/components/Layout/AuthModal/components/Login/Login.module.scss
  src/components/Layout/AuthModal/components/Register/Register.jsx
  src/components/Layout/Header/Header.jsx
  src/components/Layout/Header/Header.module.scss
  src/components/TalentPage/components/ListProofs/ListProofs.jsx
  src/context/UserContext/UserContext.jsx
  src/hoc/RequireAuth.jsx
  src/hooks/useTalent.js
  src/index.jsx
  src/services/api-services.js
Labels: frontend, User story #2

#70 61 create profile page
  src/components/Layout/Header/Header.jsx
  src/components/ProfilePage/ProfilePage.jsx
  src/components/ProfilePage/components/AcceptingModal/AcceptingModal.jsx
  src/components/ProfilePage/components/AcceptingModal/AcceptingModal.module.scss
  src/components/TalentsListPage/TalentsListPage.jsx
  src/components/TalentsListPage/components/TalentsList/components/TalentCard/TalentCard.jsx
  src/context/TalentsContext/TalentsContext.jsx
  src/services/api-services.js
Labels: frontend, User story #3, User story #4

#71 watch personal proofs
  src/components/Layout/Header/Header.jsx
  src/components/ListProofsPage/ListProofsPage.jsx
  src/components/ProfilePage/ProfilePage.jsx
  src/components/TalentPage/components/ListProofs/ListProofs.jsx
  src/components/TalentPage/components/ListProofs/ListProofs.module.scss
  src/components/TalentPage/components/ListProofs/components/ProofBlock/ProofBlock.jsx
  src/components/TalentPage/components/ListProofs/components/ProofBlock/ProofBlock.module.scss
  src/components/TalentPage/components/ListProofs/components/ProofBlock/index.js
  src/components/TalentsListPage/components/TalentsList/components/TalentCard/TalentCard.module.scss
  src/services/api-services.js
Labels: frontend, User Story #7

#72 61 create profile page
  src/components/ProfilePage/ProfilePage.jsx
  src/components/ProfilePage/ProfilePage.module.scss
  src/components/ProfilePage/components/About/About.jsx
  src/components/ProfilePage/components/About/About.module.scss
  src/components/ProfilePage/components/About/images/edit.svg
  src/components/ProfilePage/components/About/index.js
  src/components/ProfilePage/components/About/validate.js
  src/components/ProfilePage/components/TalentData/TalentData.jsx
  src/components/ProfilePage/components/TalentData/TalentData.module.scss
  src/components/ProfilePage/components/TalentData/components/Links/Links.jsx
  src/components/ProfilePage/components/TalentData/components/Links/Links.module.scss
  src/components/ProfilePage/components/TalentData/components/Links/index.js
  src/components/ProfilePage/components/TalentData/images/plus.svg
  src/components/ProfilePage/components/TalentData/index.js
  src/components/ProfilePage/components/TalentData/validate.js
  src/components/TalentPage/components/ListProofs/components/ProofBlock/ProofBlock.jsx
  src/services/api-services.js
Labels: frontend, User story #2

#74 adding personal proofs
  src/components/Layout/AuthModal/components/Login/Login.jsx
  src/components/ProfilePage/ProfilePage.jsx
  src/components/ProfilePage/ProfilePage.module.scss
  src/components/ProfilePage/components/AddingProofsForm/AddingProofsForm.jsx
  src/components/ProfilePage/components/AddingProofsForm/AddingProofsForm.module.scss
  src/components/TalentPage/components/ListProofs/ListProofs.jsx
  src/components/TalentPage/components/ListProofs/components/ProofBlock/ProofBlock.jsx
  src/services/api-services.js
  src/shared/components/Input/Input.module.scss
  src/shared/components/Textarea/Textarea.module.scss
  src/shared/images/plus.svg
Labels: frontend, User Story #9

#81 75 editing personal proofs
  src/components/ProfilePage/ProfilePage.jsx
  src/components/ProfilePage/components/AddingProofsForm/AddingProofsForm.jsx
  src/components/ProfilePage/components/AddingProofsForm/AddingProofsForm.module.scss
  src/components/ProfilePage/components/ProfileListProofs/ProfileListProofs.jsx
  src/components/ProfilePage/components/ProfileListProofs/ProfileListProofs.module.scss
  src/components/ProfilePage/components/ProfileListProofs/components/ProfileProofBlock/ProfileProofBlock.jsx
  src/components/ProfilePage/components/ProfileListProofs/components/ProfileProofBlock/ProfileProofBlock.module.scss
  src/components/ProfilePage/components/ProfileListProofs/components/ProfileProofBlock/components/DeletingProofModal/DeletingProofModal.jsx
  src/components/ProfilePage/components/ProfileListProofs/components/ProfileProofBlock/components/DeletingProofModal/DeletingProofModal.module.scss
  src/components/ProfilePage/components/ProfileListProofs/components/ProfileProofBlock/components/DeletingProofModal/index.js
  src/components/ProfilePage/components/ProfileListProofs/components/ProfileProofBlock/dropdown.js
  src/components/ProfilePage/components/ProfileListProofs/components/ProfileProofBlock/images/fire.svg
  src/components/ProfilePage/components/ProfileListProofs/components/ProfileProofBlock/images/threedots.svg
  src/components/ProfilePage/components/ProfileListProofs/components/ProfileProofBlock/index.js
  src/components/ProfilePage/components/ProfileListProofs/index.js
  src/components/TalentPage/components/ListProofs/ListProofs.jsx
  src/components/TalentPage/components/ListProofs/components/ProofBlock/ProofBlock.jsx
  src/components/TalentPage/components/ListProofs/components/ProofBlock/ProofBlock.module.scss
  src/services/api-services.js
Labels: frontend, stage 2

#82 Kudos
  src/components/ListProofsPage/ListProofsPage.jsx
  src/components/ProfilePage/ProfilePage.jsx
  src/components/ProfilePage/components/AddingProofsForm/AddingProofsForm.jsx
  src/components/ProfilePage/components/ProfileListProofs/ProfileListProofs.jsx
  src/components/ProfilePage/components/ProfileListProofs/components/ProfileProofBlock/ProfileProofBlock.jsx
  src/components/ProfilePage/components/ProfileListProofs/components/ProfileProofBlock/ProfileProofBlock.module.scss
  src/components/TalentPage/components/ListProofs/ListProofs.jsx
  src/components/TalentPage/components/ListProofs/components/ProofBlock/ProofBlock.jsx
  src/components/TalentPage/components/ListProofs/components/ProofBlock/ProofBlock.module.scss
  src/components/TalentPage/components/ListProofs/components/ProofBlock/components/Kudos.jsx
  src/components/TalentPage/components/ListProofs/components/ProofBlock/components/Kudos.module.scss
  src/services/api-services.js
Labels: frontend, stage 3, User story #3.1
